aliases:
  - &steps-for-xcode
    - checkout
    - run: pod repo update
    - run: make test|xcpretty -r junit
    - store_test_results:
        path: build/reports/
    - restore_cache:
        key: cocoapods
    - run: pod lib lint
    - save_cache:
        key: cocoapods
        paths:
          - ~/.cocoapods

  - &steps-for-swiftpm
    - checkout
    - run: git submodule update --init --recursive
    - run: swift test
    - run: brew install swiftlint && swiftlint lint --strict

  - &steps-for-linux
    - checkout
    - run: swift test

version: 2
jobs:

  xcode_9:
    macos:
      xcode: "9.0"
    steps: *steps-for-xcode

  swiftpm_4:
    macos:
      xcode: "9.0"
    steps: *steps-for-swiftpm

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps: *steps-for-linux

  xcode_9.1:
    macos:
      xcode: "9.1.0"
    steps: *steps-for-xcode

  swiftpm_4.0.2:
    macos:
      xcode: "9.1.0"
    steps: *steps-for-swiftpm

  linux_swift_4.0.2:
    docker:
      - image: norionomura/swift:402
    steps: *steps-for-linux

  xcode_9.2:
    macos:
      xcode: "9.2.0"
    steps: *steps-for-xcode

  swiftpm_4.0.3:
    macos:
      xcode: "9.2.0"
    steps: *steps-for-swiftpm

  linux_swift_4.0.3:
    docker:
      - image: norionomura/swift:403
    steps: *steps-for-linux

  linux_swift_4.1:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps: *steps-for-linux

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9
      - swiftpm_4
      - linux_swift_4
      - xcode_9.1
      - swiftpm_4.0.2
      - linux_swift_4.0.2
      - xcode_9.2
      - swiftpm_4.0.3
      - linux_swift_4.0.3
      - linux_swift_4.1
